FROM alpine
CMD ["echo", "Hello World!"]

# Build docker with:
#  docker build -t hello .
# ^ tell docker to build a docker image with the tag (-t) of hello ("." is also an important command here, dont know yet what it does)

# Run container (that has the above made image) with:
#   docker run hello